project_id = "togpcxapjuqrzbzqilbt"

[functions.ghl-contacts]
verify_jwt = false

[functions.ghl-opportunities] 
verify_jwt = false

[functions.ghl-conversations]
verify_jwt = false

[functions.ghl-emails]
verify_jwt = false