project_id = "togpcxapjuqrzbzqilbt"

[functions.ghl-contacts]
verify_jwt = true

[functions.ghl-opportunities] 
verify_jwt = true

[functions.ghl-conversations]
verify_jwt = true

[functions.ghl-emails]
verify_jwt = true

[functions.ghl-webhook]
verify_jwt = false

[functions.submit-form]
verify_jwt = false

[functions.create-patient-from-form]
verify_jwt = true

[functions.ghl-health-check]
verify_jwt = true

[functions.ghl-locations]
verify_jwt = true