-- First, let's check if the user exists and delete if needed
DELETE FROM auth.users WHERE email = 'demo@testing.com';

-- Create the demo user properly with the correct password
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  confirmation_token,
  recovery_sent_at,
  recovery_token,
  email_change_sent_at,
  email_change,
  email_change_confirm_status,
  banned_until,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  confirmed_at,
  email_change_token_current,
  email_change_confirm_status_current,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'a682ae22-1235-4ed0-b2fb-aa86ec79343b',
  'authenticated',
  'authenticated',
  'demo@testing.com',
  crypt('DemoPortfolio2024!', gen_salt('bf')),
  now(),
  now(),
  '',
  null,
  '',
  null,
  '',
  0,
  null,
  '{"provider":"email","providers":["email"]}',
  '{"first_name":"Dr. Sarah","last_name":"Martinez","role":"demo"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  now(),
  '',
  0,
  null,
  '',
  null,
  false,
  null
);