// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://togpcxapjuqrzbzqilbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvZ3BjeGFwanVxcnpienFpbGJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTIyNjYsImV4cCI6MjA2ODM4ODI2Nn0.Oq1qi4Em8-CAMMjuTtkw-YLd3QGMcqtBXGRAMgEQqF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});